---
name: Populate README.md with Github Stats

on:
    workflow_dispatch: # adds a button to execute workflow manually
    schedule:
        - cron: '0 0 * * 0' # auto-run every week
    push: # execute workflow on every push
        branches:
            - main # execute workflow on main branch

jobs:
    run-pupulate-readme-stats:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4 # an action that checks out the repository
              with:
                  fetch-depth: 0 # checkout full commit history

            - name: Generate README.md
              uses: teoxoy/profile-readme-stats@v3 # an action that gets your Github stats and generates readme file using a template
              with:
                  token: ${{ secrets.USER_TOKEN }} # picked up automatically
                  template: './templates/TEMPLATE.md' # path to template, you need to create it manually
                  readme: './README.md' # path to actual generated README.md, that will be used in your profile

            - name: Commit updated Github stats # commits an updated stats
              run: |
                  if [[ "$(git status --porcelain)" != "" ]]; then
                  git config user.name github-stats-populator-bot
                  git config user.email imagnum.satellite@gmail.com
                  git add .
                  git commit -m "chore(docs): populate README.md with updated Github stats"
                  git push
                  fi
